# Automatically generated by configure - do not modify
SRC_PATH=/home/ubuntu/Desktop/rpi4-xen-uboot/xen/tools/qemu-xen-dir/roms/vgabios
AS=aarch64-linux-gnu-as
CC=aarch64-linux-gnu-gcc --sysroot=/mnt/dom0_rpi-arm64-rootfs/ -nostdinc -isystem/mnt/dom0_rpi-arm64-rootfs/usr/lib/gcc/aarch64-linux-gnu/7/include -isystem/mnt/dom0_rpi-arm64-rootfs/usr/local/include -isystem/mnt/dom0_rpi-arm64-rootfs/usr/lib/gcc/aarch64-linux-gnu/7/include-fixed -isystem/mnt/dom0_rpi-arm64-rootfs/usr/include/aarch64-linux-gnu -isystem/mnt/dom0_rpi-arm64-rootfs/usr/include -B/mnt/dom0_rpi-arm64-rootfs/lib/aarch64-linux-gnu -B/mnt/dom0_rpi-arm64-rootfs/usr/lib/aarch64-linux-gnu
BCC=bcc
CPP=aarch64-linux-gnu-gcc --sysroot=/mnt/dom0_rpi-arm64-rootfs/ -nostdinc -isystem/mnt/dom0_rpi-arm64-rootfs/usr/lib/gcc/aarch64-linux-gnu/7/include -isystem/mnt/dom0_rpi-arm64-rootfs/usr/local/include -isystem/mnt/dom0_rpi-arm64-rootfs/usr/lib/gcc/aarch64-linux-gnu/7/include-fixed -isystem/mnt/dom0_rpi-arm64-rootfs/usr/include/aarch64-linux-gnu -isystem/mnt/dom0_rpi-arm64-rootfs/usr/include -B/mnt/dom0_rpi-arm64-rootfs/lib/aarch64-linux-gnu -B/mnt/dom0_rpi-arm64-rootfs/usr/lib/aarch64-linux-gnu -E
OBJCOPY=objcopy
IASL=iasl
LD=aarch64-linux-gnu-ld
